[project]
name = "openapi-to-cli"
authors = [{ name = "Joshua Oliphant", email = "joshua.oliphant@hey.com" }]
version = "0.1.0"
description = "A CLI generator for OpenAPI specs"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.3.0",
    "jinja2>=3.1.6",
    "openapi-python-client>=0.28.3",
    "pydantic>=2.13.3",
    "pyyaml>=6.0.3",
]

[dependency-groups]
dev = [
    "pytest>=8.3.3",
]

[tool.pyright]
venvPath = "."
venv = ".venv"
